const STORAGE_KEYS = {
  BSHELL_PASSCODE_AUTH: 'BSHELL_PASSCODE_AUTH',
  BSHELL_PASSCODE_PROMPT_PENDING: 'BSHELL_PASSCODE_PROMPT_PENDING',
}

const APP_VERSION = '1.0.0'

module.exports = {
  STORAGE_KEYS,
  APP_VERSION,
}
